services:
  piston:
    image: ghcr.io/engineer-man/piston
    container_name: piston
    restart: always
    privileged: true
    ports:
      - "2000:2000"
    volumes:
      - ./piston_data:/piston/data
    tmpfs:
      - /tmp:exec,mode=777